"""change_timestamp_to_tz6

Revision ID: 3d4644498c2a
Revises: 4c8e3e464b55
Create Date: 2026-03-12 01:11:35.147460

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d4644498c2a"
down_revision: Union[str, Sequence[str], None] = "4c8e3e464b55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_markets",
        "status",
        existing_type=postgresql.ENUM(
            "GENERATED", "IN_PROGRESS", "COMPLETED", "DECLINED", name="orderstatus"
        ),
        type_=sa.Enum(
            "GENERATED",
            "CONFIRMED",
            "PAID",
            "DECLINED",
            "COMPLETED",
            name="orderstatus",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "status",
        existing_type=postgresql.ENUM(
            "GENERATED", "IN_PROGRESS", "COMPLETED", "DECLINED", name="orderstatus"
        ),
        type_=sa.Enum(
            "GENERATED",
            "IN_PROGRESS",
            "COMPLETED",
            "DECLINED",
            name="orderstatus",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "status",
        existing_type=sa.Enum(
            "GENERATED",
            "IN_PROGRESS",
            "COMPLETED",
            "DECLINED",
            name="orderstatus",
            native_enum=False,
        ),
        type_=postgresql.ENUM(
            "GENERATED", "IN_PROGRESS", "COMPLETED", "DECLINED", name="orderstatus"
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "order_markets",
        "status",
        existing_type=sa.Enum(
            "GENERATED",
            "CONFIRMED",
            "PAID",
            "DECLINED",
            "COMPLETED",
            name="orderstatus",
            native_enum=False,
        ),
        type_=postgresql.ENUM(
            "GENERATED", "IN_PROGRESS", "COMPLETED", "DECLINED", name="orderstatus"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
