"""add user_tokens

Revision ID: a7b6edf55a8e
Revises: e33d919c6875
Create Date: 2026-03-11 23:01:18.453132

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7b6edf55a8e"
down_revision: Union[str, Sequence[str], None] = "e33d919c6875"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("userId", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("expiresAt", sa.TIMESTAMP(), nullable=False),
        sa.Column("createdAt", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(["userId"], ["users.userId"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_tokens_token"), "user_tokens", ["token"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_tokens_token"), table_name="user_tokens")
    op.drop_table("user_tokens")
    # ### end Alembic commands ###
