"""fix_user_created_at_default

Revision ID: ad7ac952acd0
Revises: a7b6edf55a8e
Create Date: 2026-03-11 23:36:45.855226

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad7ac952acd0"
down_revision: Union[str, Sequence[str], None] = "a7b6edf55a8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("OrderItems", sa.Column("orderId", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        None, "OrderItems", "orders", ["orderId"], ["orderId"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "OrderItems", type_="foreignkey")
    op.drop_column("OrderItems", "orderId")
    # ### end Alembic commands ###
