"""create all tables

Revision ID: e33d919c6875
Revises:
Create Date: 2026-03-11 22:30:38.749032

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e33d919c6875"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("userId", sa.Uuid(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("passwordHash", sa.String(), nullable=False),
        sa.Column("firstName", sa.String(), nullable=False),
        sa.Column("lastName", sa.String(), nullable=False),
        sa.Column("patronymic", sa.String(), nullable=True),
        sa.Column("dateOfBirth", sa.Date(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("telegram", sa.String(), nullable=True),
        sa.Column("telegramChatId", sa.String(), nullable=True),
        sa.Column("isSeller", sa.Boolean(), nullable=False),
        sa.Column("createdAt", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("userId"),
        sa.UniqueConstraint("login"),
        sa.UniqueConstraint("telegram"),
        sa.UniqueConstraint("telegramChatId"),
    )
    op.create_index(op.f("ix_users_isSeller"), "users", ["isSeller"], unique=False)
    op.create_table(
        "cart",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("userId", sa.Uuid(), nullable=False),
        sa.Column("createdAt", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.userId"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("userId"),
    )
    op.create_table(
        "market",
        sa.Column("marketId", sa.Uuid(), nullable=False),
        sa.Column("userId", sa.Uuid(), nullable=False),
        sa.Column("marketName", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("createdAt", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.userId"],
        ),
        sa.PrimaryKeyConstraint("marketId"),
        sa.UniqueConstraint("marketName"),
    )
    op.create_index(op.f("ix_market_userId"), "market", ["userId"], unique=False)
    op.create_table(
        "orders",
        sa.Column("orderId", sa.Uuid(), nullable=False),
        sa.Column("userId", sa.Uuid(), nullable=False),
        sa.Column("totalPrice", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("deliveryAddress", sa.String(), nullable=False),
        sa.Column("deliveryCity", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("deliveryComment", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "GENERATED", "IN_PROGRESS", "COMPLETED", "DECLINED", name="orderstatus"
            ),
            nullable=False,
        ),
        sa.Column("createdAt", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.userId"],
        ),
        sa.PrimaryKeyConstraint("orderId"),
        sa.UniqueConstraint("orderId", "userId", name="unique_order_user"),
    )
    op.create_table(
        "order_markets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("orderId", sa.Uuid(), nullable=False),
        sa.Column("marketId", sa.Uuid(), nullable=False),
        sa.Column("totalPrice", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "GENERATED",
                "CONFIRMED",
                "PAID",
                "DECLINED",
                "COMPLETED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["marketId"],
            ["market.marketId"],
        ),
        sa.ForeignKeyConstraint(
            ["orderId"],
            ["orders.orderId"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("orderId", "marketId", name="unique_order_market"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("marketId", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "electronics",
                "clothing",
                "food",
                "home",
                "beauty",
                "sports",
                "books",
                "other",
                name="productcategory",
            ),
            nullable=False,
        ),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("img", sa.String(), nullable=False),
        sa.Column("available", sa.INTEGER(), nullable=False),
        sa.Column("createdAt", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["marketId"],
            ["market.marketId"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_products_category"), "products", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_products_marketId"), "products", ["marketId"], unique=False
    )
    op.create_table(
        "OrderItems",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("orderMarketId", sa.Uuid(), nullable=False),
        sa.Column("productId", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.INTEGER(), nullable=False),
        sa.Column("priceAtPurchase", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["orderMarketId"],
            ["order_markets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["productId"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cartItems",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cartId", sa.Uuid(), nullable=False),
        sa.Column("productId", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cartId"],
            ["cart.id"],
        ),
        sa.ForeignKeyConstraint(
            ["productId"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cartItems")
    op.drop_table("OrderItems")
    op.drop_index(op.f("ix_products_marketId"), table_name="products")
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_table("products")
    op.drop_table("order_markets")
    op.drop_table("orders")
    op.drop_index(op.f("ix_market_userId"), table_name="market")
    op.drop_table("market")
    op.drop_table("cart")
    op.drop_index(op.f("ix_users_isSeller"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
