"""all tables

Revision ID: f50dae050f7c
Revises: 75bb647a625a
Create Date: 2026-04-01 01:35:55.030909

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f50dae050f7c"
down_revision: Union[str, Sequence[str], None] = "75bb647a625a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cartItems",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cartId", sa.Uuid(), nullable=False),
        sa.Column("productId", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cartId"],
            ["cart.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_markets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("orderId", sa.Uuid(), nullable=False),
        sa.Column("marketId", sa.UUID(), nullable=False),
        sa.Column("totalPrice", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["orderId"],
            ["orders.orderId"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("orderId", "marketId", name="unique_order_market"),
    )
    op.create_table(
        "OrderItems",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("orderId", sa.Uuid(), nullable=False),
        sa.Column("orderMarketId", sa.Uuid(), nullable=False),
        sa.Column("productId", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.INTEGER(), nullable=False),
        sa.Column("priceAtPurchase", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["orderId"], ["orders.orderId"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["orderMarketId"],
            ["order_markets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("OrderItems")
    op.drop_table("order_markets")
    op.drop_table("cartItems")
    # ### end Alembic commands ###
